#------------------------------------------------------------------------------
# <auto-generated>
#    Changes to this file will be lost if the code is regenerated.
# </auto-generated>
#------------------------------------------------------------------------------
spring:
  application:
    name: ${artifactId}
  datasource:
    url: ${databaseUrl}
    username: ${databasePassword}
    password: ${databaseUsername}
    driverClassName : com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
        ddl-auto: create-drop
    database-platform : org.hibernate.dialect.MySQL5Dialect

server:
  port: ${port}