package ${enum.typePackage};

//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public enum ${enum.name?cap_first} {
<#list enum.values as value>
	${value}<#sep>,</#sep>
</#list>
}