package ${package};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

@SpringBootApplication
public class ${name} {

	public static void main(String[] args){
	
		SpringApplication.run(${name}.class, args);
	} 
	
}