package ${class.typePackage};

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import ${class.typePackage?keep_before_last(".")}.model.*;

//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public interface ${class.name}Repository extends JpaRepository<${class.name}, Long> {
	
	${class.name} findOneById(Long id);
	
}



